spring:
  banner:
    location: classpath:banner.txt
  application:
    name: mapping_service
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true