server:
  port: 8089
spring:
  banner:
    location: classpath:banner.txt

  application:
    name: alerting_service

  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: notification_alert_exchange
    queue: topic_alert_mail
    routingkey: mailroutingkey

  mail:
    host: smtp.gmail.com
    port: 587
    username: survey.augur@gmail.com
    password: xbyxeruheunuypaf
    #Other properties
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true